sudo: false
language: python
python:
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=amy,api,workshops manage.py test
after_success:
  coveralls
